// Code generated by "stringer -type Op -trimprefix Op"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpLiteral-0]
	_ = x[OpConcat-1]
	_ = x[OpAlternate-2]
}

const _Op_name = "LiteralConcatAlternate"

var _Op_index = [...]uint8{0, 7, 13, 22}

func (i Op) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Op_index)-1 {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[idx]:_Op_index[idx+1]]
}
